Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=240
Job counts:
	count	jobs
	1	all
	413	classify_replicated_trajectories
	414

[Sat May 15 15:03:13 2021]
rule classify_replicated_trajectories:
    input: results/Rad21/2021_04_27_Fbn2_RAD21__twohoursIAA_488nm_0p5_561nm_0p05_SC8_2X_30z_250nm_780V_365T_20s_movie3-01.czi.tracks_corrected.csv, results/Rad21/2021_04_27_Fbn2_RAD21__twohoursIAA_488nm_0p5_561nm_0p05_SC8_2X_30z_250nm_780V_365T_20s_movie3-01.czi.dot_volumes.pkl, ml_models/Replication_model_2021_04_14_hugo_classifications.h5, ml_models/4D_model_2021_04_08_mixedInputClean_v2_doubleClassification.h5
    output: results/Rad21/2021_04_27_Fbn2_RAD21__twohoursIAA_488nm_0p5_561nm_0p05_SC8_2X_30z_250nm_780V_365T_20s_movie3-01.czi.tracks_ML.csv
    jobid: 1763
    wildcards: sample_group=Rad21, sample_name=2021_04_27_Fbn2_RAD21__twohoursIAA_488nm_0p5_561nm_0p05_SC8_2X_30z_250nm_780V_365T_20s_movie3-01.czi

Terminating processes on user request, this might take some time.
[Sat May 15 15:03:19 2021]
Error in rule classify_replicated_trajectories:
    jobid: 1763
    output: results/Rad21/2021_04_27_Fbn2_RAD21__twohoursIAA_488nm_0p5_561nm_0p05_SC8_2X_30z_250nm_780V_365T_20s_movie3-01.czi.tracks_ML.csv

RuleException:
CalledProcessError in line 159 of /home/hbrandao/libs/data_analysis_Fbn2/snakemake/workflow/snakefile_beads:
Command 'set -euo pipefail;  /home/hbrandao/anaconda3/bin/python /home/hbrandao/libs/data_analysis_Fbn2/snakemake/workflow/.snakemake/scripts/tmp09cdxj5w.classify_dots_by_CNN.py' returned non-zero exit status 1.
  File "/home/hbrandao/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2347, in run_wrapper
  File "/home/hbrandao/libs/data_analysis_Fbn2/snakemake/workflow/snakefile_beads", line 159, in __rule_classify_replicated_trajectories
  File "/home/hbrandao/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/hbrandao/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/hbrandao/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/hbrandao/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2359, in run_wrapper
Complete log: /home/hbrandao/libs/data_analysis_Fbn2/snakemake/workflow/.snakemake/log/2021-05-15T150259.752404.snakemake.log
